---
- name: Squid | Create config directory
  ansible.builtin.file:
    dest: "{{ squid_conf_dir }}"
    state: directory
    mode: "0777"
    owner: root
    group: root

- name: Squid | Ensure squid.conf template
  ansible.builtin.template:
    src: squid.conf.j2
    dest: "{{ squid_conf_dir }}/squid.conf"
    mode: "0644"
    owner: root
    group: root

- name: Squid | Check container registry type
  assert:
    that: 
      - squid_type_private_registry in ['yc_cr']
    fail_msg: >
      Invalid squid_type_private_registry: '{{ squid_type_private_registry }}'.
      Allowed: 'yc_cr'.
  when: squid_use_private_registry

- name: Squid | Create IAM token in registry yc_cr
  ansible.builtin.shell: |
    curl --header Metadata-Flavor:Google 169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token | \
    cut -f1 -d',' | \
    cut -f2 -d':' | \
    tr -d '"' 
  when: squid_use_private_registry and squid_type_private_registry == "yc_cr"
  register: yc_cr_registry_token

- name: Squid | Get IAM token in registry yc_cr
  ansible.builtin.set_fact:
    squid_yc_cr_registry_token: "{{ yc_cr_registry_token.stdout }}"
  when: squid_use_private_registry and squid_type_private_registry == "yc_cr"

- name: Squid | Login into private docker registry
  community.docker.docker_login:
    registry_url: cr.yandex
    username: iam
    password: "{{ squid_yc_cr_registry_token }}"
    reauthorize: true
  when: squid_use_private_registry and squid_type_private_registry == "yc_cr"

- name: Squid | Start docker squid container
  community.docker.docker_compose_v2:
    state: present
    project_name: squid_proxy
    definition:
      services:
        squid-proxy:
          image: "{{ squid_docker_image }}:{{ squid_version }}"
          container_name: "{{ squid_container_name }}"
          ports: "{{ squid_ports }}"
          restart: always
          volumes: "{{ squid_volumes }}"
      networks:
        default:
          external: true
          name: "{{ squid_docker_network_name }}"
  when: not squid_swarm_cluster or squid_swarm_manager is undefined

- name: Squid | Deploy squid to docker swarm
  block:
    - name: Ensure pip installation
      package:
        name: "python3-pip"
        state: present

    - name: Install newer version of pip itself
      pip:
        name: "pip"
        state: latest
        executable: pip3
      when:
        - ansible_distribution == "ubuntu"
        - ansible_distribution_major_version != 24

    - name: Install jsondiff from pip
      pip:
        name: "jsondiff"
        state: present
        executable: pip3
      when:
        - ansible_distribution == "ubuntu"
        - ansible_distribution_major_version != 24

    - name: Ensure jsondiff
      package:
        name: "python3-jsondiff"
        state: present
      when:
        - ansible_distribution == "ubuntu"
        - ansible_distribution_major_version == 24

    - name: Deploy squid docker container in swarm
      community.docker.docker_stack:
        state: present
        name: "{{ squid_stack_name | default('squid')}}"
        with_registry_auth: yes
        compose:
          - services: |
              {{
                {
                  item.name: {
                    "image": squid_docker_image + ":" + squid_version,
                    "hostname": item.name,
                    "labels": squid_docker_labels | default([]),
                    "deploy": squid_swarm_deploy,
                    "volumes": squid_volumes,
                    "ports": squid_ports
                  }
                }
              }}
            networks:
              default:
                external:
                  name: "{{ squid_docker_network_name }}"
      run_once: True
      loop: "{{ squid_docker_services }}"
  delegate_to: "{{ squid_swarm_manager }}"
  when: 
    - squid_swarm_cluster
    - squid_swarm_manager is defined
