---
- name: Squid | Setup container
  include_tasks: docker.yml
  tags:
    - install
  when: squid_dockerize

- name: Squid | Install service
  include_tasks: service.yml
  tags:
    - install
  when: not squid_dockerize
